# Generated by Django 5.1.2 on 2025-09-08 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('anofabricacao', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=18, unique=True)),
                ('chassi', models.CharField(max_length=18, unique=True)),
                ('is_ativo', models.BooleanField(default=False)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.fabricante')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
    ]
